packages:
  - packages/**/*
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@dunky.dev/native-state-machine@0.3.2'
  - '@dunky.dev/react-state-machine@0.3.2'
  - '@dunky.dev/state-machine-bindings@0.3.2'
  - '@dunky.dev/state-machine-utils@0.3.2'
  - '@dunky.dev/state-machine@0.3.2'
  - '@dunky.dev/solid-state-machine@0.4.0'
  - '@dom-expressions/babel-plugin-jsx@0.50.0-next.43'
  - '@solidjs/signals@2.0.0-rc.1'
  - '@solidjs/web@2.0.0-rc.1'
  - babel-preset-solid@2.0.0-rc.1
  - solid-js@2.0.0-rc.1
publicHoistPattern:
  - '*storybook*'
