// storybook.requires is generated by the metro withStorybook wrapper (or
// `sb-rn-get-stories`) from main.ts's stories glob — gitignored, never edited.
import { view } from './storybook.requires'

const StorybookUIRoot: ReturnType<typeof view.getStorybookUI> = view.getStorybookUI({})

export default StorybookUIRoot
