import AsyncStorage from '@react-native-async-storage/async-storage'
// storybook.requires is generated by the metro withStorybook wrapper (or
// `sb-rn-get-stories`) from main.ts's stories glob — gitignored, never edited.
import { view } from './storybook.requires'

const StorybookUIRoot: ReturnType<typeof view.getStorybookUI> = view.getStorybookUI({
  // Persists the selected story across reloads.
  storage: {
    getItem: AsyncStorage.getItem,
    setItem: AsyncStorage.setItem,
  },
})

export default StorybookUIRoot
